### ISSUE TITLE
Typo creating a compiler error in wand2.c Line 311. 

### ISSUE THREAD

**Issue by esotericreference** [shmup/wander#4]
wand2.c:311:1: error: unknown type name 'in'
in                                     /\* put wrd vals in w[0], w[1],  ... */

"in" should just be "int".

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by ahope1** [comment]
Yep, Peter acknowledged that that was indeed a typo! I corrected it in the version I uploaded and linked to from my blog: https://ahopeful.wordpress.com/2015/04/22/wander-1974-a-lost-mainframe-game-is-found/#update1

**Comment by esotericreference** [comment]
I don't have access or I'd just push a revision really quickly. Would also
be nice to clean up the compiler warnings so that future development is
smoother.

**Comment by shmup** [comment]
It was addressed in a pull request and now builds for me on OS X 10.10.2 

Good eye :+1: https://github.com/shmup/wander/commit/886b43c571517c9a203ee4b9a4a441982ac227b1
