### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by brouhaha** [shmup/wander#9]
Unless I've overlooked it, there's no license grant. If it's not too much trouble, could someone who is in touch with Peter ask whether he'd be willing to adopt an open source license?  I'd like to contribute a wander package to the official package repository for a Linux distribution I use, but can't without confirmation of a license.

**Comment by shmup** [comment]
Well, I can at least try shooting him an email on the one he provides on his homepage. I'll do that today.

**Comment by shmup** [comment]
So I got a reply, and he's definitely OK with an open source license, but cared about the license remaining intact (copyleft). I suggested GNU GPLv3 http://choosealicense.com/licenses/gpl-3.0/

Curious if you had any other thoughts, @brouhaha and whoever else.

**Comment by brouhaha** [comment]
I think GPLv3 is an excellent choice.

**Comment by shmup** [comment]
Better late than never, @brouhaha ! hah

closed with https://github.com/shmup/wander/commit/d08e91ff006817aad6fc2bc55e0818dbc9f4b0bb
